### ISSUE TITLE
The POM for org.databene:maven-benerator-plugin:jar:0.9.8 is missing,  no dependency information available

### ISSUE THREAD

**Issue by bavaddin** [vishalmanohar/databene-benerator#1]
Hello vishal,

I am working on benerator to generate test data,after typing the 'mvn benerator:generate' on the command line.
I am getting the following errors, can you please guide me in the solution.
warning:

The POM for org.databene:maven-benerator-plugin:jar:0.9.8 is missing, 
no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.databene:maven-benerator-plugin:0.9.8: 
Plugin org.databene:maven-benerator-plugin:0.9.8 or one of its dependencies could not be resolved: 
Failure to find org.databene:maven-benerator-plugin:jar:0.9.8 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

error : 

No plugin found for prefix 'benerator' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\sudarsan.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
org.apache.maven.plugin.prefix.NoPluginFoundForPrefixException: No plugin found for prefix 'benerator' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\sudarsan.m2\repository), central (https://repo.maven.apache.org/maven2)]

Thanks in advance.

**Comment by vishalnaik** [comment]
It doesn't look like there is a 0.9.8 version of benerator.

http://databene.org/m2/org/databene/maven-benerator-plugin/

**Comment by bavaddin** [comment]
I had downloaded the tool from http://databene.org/databene-benerator this site only,

i have also added the jar file from 
http://mvnrepository.com/artifact/org.databene/databene-benerator/0.9.8 to my reposiratory

can you plz suggest any ways to resolve the issue.

**Comment by vishalmanohar** [comment]
Please contact the author of the tool himself from that website. This github repo is just a fork of the original tool and is not being maintained currently.

**Comment by bavaddin** [comment]
Hi,
<bean id="dtGen" class="DateTimeGenerator">
        <property name='minDate'          value='2011-09-30'/>
        <property name='maxDate'          value='2011-12-30'/>
                 <property name='dateGranularity'  value='00-00-02'  />
        <property name='dateDistribution' value='random'    />  
</bean>
I am able to generate random date by using above snippet, but i want to give weights to each month separately so that i can create variations in data generation. can you plz help me in assigning weights to  months.
your help would be appreciated.

Regards,
Baba

**Comment by bavaddin** [comment]
sorry my code was not displayed in the chat box.
